### ISSUE TITLE
Consider removing unused code

### ISSUE THREAD

**Issue by WennderSantos** [nubank/basic-microservice-example#3]
I know it is just a sample, but if people use this as a material of study, an unused code can be a bit confusing.

I think this line it's not being used anywhere.

https://github.com/nubank/basic-microservice-example/blob/6578a850c98e4b7fa4f6045054b2799f15e5fc38/src/basic_microservice_example/components.clj#L18

PS: Thanks for this sample, it's being realy useful ;)

**Comment by matheusfrantz** [comment]
Fixed in [#8](https://github.com/nubank/basic-microservice-example/pull/8/files). Thank you!
